FROM python:3.9-alpine

RUN apk --no-cache add build-base git
RUN pip install pipenv

WORKDIR /docs
COPY Pipfile Pipfile.lock ./

RUN pipenv install

STOPSIGNAL SIGINT
CMD ["pipenv", "run", "mkdocs", "serve", "-a", "0.0.0.0:8000"]
