version: '3'
services:
  app:
    image: ghcr.io/netsoc/docs:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/docs
      - ../cli/docs:/docs/docs/cli
      - ../webspaced/docs:/docs/docs/webspaced
    ports:
      - 8000:8000
