site_name: Netsoc
site_url: https://docs.netsoc.ie
repo_url: https://github.com/netsoc/docs
repo_name: netsoc/docs
use_directory_urls: true
theme:
  name: material
  logo: assets/nat-white.svg
  favicon: assets/nat.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  font:
    code: Source Code Pro
markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - macros
  - awesome-pages
  - search
  - git-revision-date-localized:
      type: timeago

extra:
  github_org: https://github.com/netsoc
