site_name: Netsoc
repo_url: https://github.com/netsoc/docs
repo_name: netsoc/docs
theme:
  name: material
  logo: assets/nat-white.svg
  favicon: assets/nat.png
  features:
    - navigation.tabs
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - macros
  - awesome-pages
  - git-revision-date-localized:
      type: timeago

extra:
  github_org: https://github.com/netsoc
