name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - charts/**

jobs:
  docker:
    runs-on: ubuntu-20.04

    env:
      CR_PAT_USER: devplayer0
      REPO: ghcr.io/netsoc/docs

    steps:
      - uses: actions/checkout@v2
        with:
          # So that the build can see the history and note the update times
          fetch-depth: 0

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.CR_PAT_USER }}
          password: ${{ secrets.CI_PAT }}

      - id: vars
        name: Generate build vars
        run: |
          SHA="${{ github.sha }}"
          echo "::set-output name=tag::"${SHA:0:8}-$(date +%s)Z""

      # Use plain Docker here, buildx misses .git
      - name: Build
        run: docker build -t "${{ env.REPO }}:${{ steps.vars.outputs.tag }}" -t "${{ env.REPO }}:latest" .

      - name: Push
        run: docker push --all-tags "$REPO"
