name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - charts/**

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      CR_PAT_USER: devplayer0
      REPO: ghcr.io/netsoc/docs

    steps:
      - uses: actions/checkout@v2
        with:
          # So that the build can see the history and note the update times
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.CR_PAT_USER }}
          password: ${{ secrets.CI_PAT }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: |
            ${{ env.REPO }}:${{ github.sha }}
            ${{ env.REPO }}:latest

      # Pushing to an existing tag doesn't seem to work with buildx :(
      - name: Push
        run: docker push "$REPO"
